# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8881d6a131dc709966c5c07f1a9245749ad3c891012ca00781d9053fa6d2fb18a915aa0fc2ddd138bab5ae7f1cbabac230dc2c98df3dcba5b899309012211cf9

test:
  secret_key_base: 7d0046f9bfc9e0b7dd58c914461076aa7e62d7563680e442401c5e72ada55c7b1c51f5709b6fd8628d3b73fb070d08b37b0e7731d0af8718d134932a1edc250f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
